#if !canImport(ObjectiveC)
import XCTest

extension ConsoleMenuControllerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConsoleMenuControllerTests = [
        ("testExitMenu", testExitMenu),
        ("testInvalidMenuIndex", testInvalidMenuIndex),
        ("testManyChoicedMenu", testManyChoicedMenu),
        ("testNoMemoryCyclesInMenuBuilding", testNoMemoryCyclesInMenuBuilding),
        ("testNoMemoryCyclesInMenuWithinMenuBuilding", testNoMemoryCyclesInMenuWithinMenuBuilding),
    ]
}

extension PagesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PagesTests = [
        ("testCanHandleEmptyInput", testCanHandleEmptyInput),
        ("testEmptyLineQuitsPageMenu", testEmptyLineQuitsPageMenu),
        ("testEmptyLineQuitsPageMenuWithCommand", testEmptyLineQuitsPageMenuWithCommand),
        ("testEmptyPages", testEmptyPages),
        ("testModifyPagesAction", testModifyPagesAction),
        ("testNavigatingPagesRelativelyDoesntOverflow", testNavigatingPagesRelativelyDoesntOverflow),
        ("testNumbersWithPlusAndMinusArePageNavigationAndNotCommandInputs", testNumbersWithPlusAndMinusArePageNavigationAndNotCommandInputs),
        ("testPages", testPages),
        ("testPagesWithColumns", testPagesWithColumns),
        ("testPagesWithPaging", testPagesWithPaging),
        ("testPass0ToQuitPagesWithCommands", testPass0ToQuitPagesWithCommands),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ConsoleMenuControllerTests.__allTests__ConsoleMenuControllerTests),
        testCase(PagesTests.__allTests__PagesTests),
    ]
}
#endif
